### ISSUE TITLE
Receiving news feed is quite slow

### ISSUE THREAD

**Issue by GirafiStudios** [wenzhixin/github-news-feed#3]
At the moment I have both Github News Feed and Github Notifier installed. After I have been using both for a while I disvovered that Github Notifier always shows the notification a good while before Github News Feed does.
Do you think you would be able to do anything about that?

Github Notifier uses an access token, could be what is making it much faster?

**Comment by wenzhixin** [comment]
Github News Feed needn't use user's access token, so we update the notification [in 5 minutes](https://github.com/wenzhixin/github-news-feed/blob/master/src/js/background.js#L5), I think it is enough to receive notifications. What do you think?
