### ISSUE TITLE
New header.

### ISSUE THREAD

**Issue by GirafiStudios** [wenzhixin/github-news-feed#6]
Hey. First of all I want to thank you for making this amazing Google Chrome plugin! :)
It seems that you added a new header earlier today, it looks very messy to me. I'm not even sure if it is supposed to look like that. Would it somehow be possible for me to disable that? :)
I use Github News Feed everyday and check it very frequently - similiar to how often I check Twitter (Every 10 minutes or so). The header takes up a lot of space, which makes it harder to get a quick overview over what is new.
I hope you will take my point of view into consideration!

Screenshot of how the header looks for me: http://prnt.sc/bn6knx

**Comment by wenzhixin** [comment]
Thanks for your feedback.

**Comment by wenzhixin** [comment]
different with you:

![image](https://cloud.githubusercontent.com/assets/2117018/16545828/257254ae-4169-11e6-8afc-e1d720c72f44.png)

**Comment by GirafiStudios** [comment]
Looks much better, good job! ^^

**Comment by wenzhixin** [comment]
Have you solved your problem?

**Comment by GirafiStudios** [comment]
Ohh, what you were saying that it looked diffrent for me, than it was supposed to?
And no it is not fixed for me, I even tried to re-install it.

EDIT: Could it be, that i'm a part of an orginazation?

**Comment by wenzhixin** [comment]
OK, let me test it.

**Comment by wenzhixin** [comment]
Sorry, it's late to fix this bug. Fixed in v1.0.8
