### ISSUE TITLE
I keep getting "Login" button

### ISSUE THREAD

**Issue by inakiabt** [wenzhixin/github-news-feed#7]
Two days ago I started to get "Login" button when I click the extension when I'm already logged in on Github (I didn't logged out, BTW)

**Comment by julkue** [comment]
@inakiabt Do you have the same problem with [this extension](https://chrome.google.com/webstore/detail/news-feed-for-github/gbpajmknkcgjeinfbmfeiafhogbhgkjh)?

**Comment by inakiabt** [comment]
I don't have it installed. I want only to use this extension.

**Comment by julkue** [comment]
If this extension also reports a problem it's not a problem of the extension.

**Comment by inakiabt** [comment]
It's back now.
